### ISSUE TITLE
Added Multi Shift Register Suppoprt

### ISSUE THREAD

**Issue by davidleedom** [adafruit/Adafruit_CircuitPython_74HC595#15]
I updated the library to support multiple Shift Registers. 

I'm happy to share, or even have you guys to just take a look  and update the official library.

**Comment by ladyada** [comment]
PRs always welcome :)
https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library

**Comment by davidleedom** [comment]
Sadly this is my first pull request.  So I may not have done things correctly.  Let me know if I need to do things differently.

**Comment by jposada202020** [comment]
@davidleedom I think you PR https://github.com/adafruit/Adafruit_CircuitPython_74HC595/pull/17 was merged on , can this issue be closed?

**Comment by davidleedom** [comment]
I'll take a look and close it today.

**Comment by jposada202020** [comment]
@davidleedom Awesome Thanks
