### ISSUE TITLE
Daisy Chain Example

### ISSUE THREAD

**Issue by Chao8219** [adafruit/Adafruit_CircuitPython_74HC595#21]
Hi, Dear All, 

I am wondering if more examples of daisy chain 74HC595 are needed. The PR #17 is straight-forward, but no examples are given.

The test I have is based on one [ItsyBitsy M0](https://www.adafruit.com/product/3727), one level shifter [74AHCT125](https://www.adafruit.com/product/1787), two [74HC595](https://www.adafruit.com/product/450), one [10 Segment Light Bar](https://www.adafruit.com/product/1921).

I also did a Fritzing diagram to show wiring.

Just let me know your thoughts. Thanks!

Best,
Chao

**Comment by ladyada** [comment]
example PRs are always welcome!

**Comment by dhalbert** [comment]
Fixed by #22.
